### ISSUE TITLE
Connect "Get Involved" form submissions to Netlify Forms or Google Forms

### ISSUE THREAD

**Issue by factcondenser** [cityofaustin/census2020#75] opened 2020-01-23 01:50 UTC
See the form here: https://atx-census-2020.netlify.com/en/get-involved

The component is here: https://github.com/cityofaustin/census2020/blob/master/gatsby/src/components/info.js

**Comment by mateoclarke** [comment] 2020-01-24 02:33
This is basically a dupe of #52 so I'm closing the other one.

**Closed as completed** 2020-02-01 03:53 UTC
